### PR TITLE
bug fix in has() function.

### PR DESCRIPTION
**Pull request by nayzo**

### CODE REVIEW

**Comment by nayzo** [comment]
Hello @minwork 
Could you merge this fix and tag a new release please ?

**Comment by minwork** [comment]
Hello,

thanks for the PR. Could you post an example when `has` is not behaving as expected which is the reason for those changes?

**Comment by nayzo** [comment]
Hello,

Sure here an example:

```
$array = array('content' => 'some message!');

Arr::has($array, 'content.foo')

==> Warning: array_key_exists() expects parameter 2 to be array, string given
```

More details with a try catch:

```
foreach ($keysArray as $key) {
            try {
                if (!array_key_exists($key, $tmp)) {
                    return false;
                }
            } catch (\Exception $e) {
                var_dump($e->getMessage(), $key, $tmp, $keysArray);die;
            }
            $tmp = $tmp[$key];
        }

==>  "Warning: array_key_exists() expects parameter 2 to be array, string given" 
"foo" 
"some message!" 
{ [0]=> "content" [1]=> "foo" }
```
Hope it's more clear now.
Thanks.

**Comment by minwork** [comment]
@nayzo Thanks for the example, resolved by #3

**Comment by nayzo** [comment]
**Could you tag a new Release ?**

**Comment by minwork** [comment]
Already did, v1.13.3 (you can find it in tags section)

**Pull request closed without merging**
